# Generated by Django 4.1.1 on 2022-09-08 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='category',
            field=models.CharField(max_length=255),
            preserve_default=False,
        ),
    ]
