# Generated by Django 4.1.1 on 2022-09-09 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_transactions_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='status',
            field=models.CharField(default='Not Done', max_length=255),
        ),
    ]
