# Generated by Django 4.1.1 on 2022-09-09 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0003_alter_todolist_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='ride_no',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
