# Generated by Django 4.1 on 2022-09-06 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Taxi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_plate', models.CharField(max_length=255, unique=True)),
                ('model', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('seats', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_no', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('img', models.ImageField(default='placeholder.jpeg', upload_to='d_img')),
                ('contacts', models.CharField(max_length=255)),
                ('taxi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='driver.taxi')),
            ],
        ),
    ]
