# Generated by Django 4.1.1 on 2022-09-08 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passenger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiring',
            name='reference',
            field=models.CharField(default="#####",max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
