# Generated by Django 4.1.1 on 2022-09-09 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passenger', '0003_alter_hiring_passenger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='passenger_no',
            field=models.CharField(max_length=255),
        ),
    ]
